<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>icons\Bearnst_StareBG.ico</ApplicationIcon>
	</PropertyGroup>

  <ItemGroup>
    <None Remove="icons\bearnst_Connected.ico" />
    <None Remove="icons\bearnst_error_DisConnected.ico" />
    <None Remove="icons\Bearnst_StareBG.ico" />
    <None Remove="icons\bearnst_Started.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.VsixColorCompiler" Version="17.0.31709.430" />
  </ItemGroup>

	<ItemGroup>
		<None Remove="icons\bearnst_Connected.ico" />
		<None Remove="icons\bearnst_error_DisConnected.ico" />
		<None Remove="icons\Bearnst_StareBG.ico" />
		<None Remove="icons\bearnst_Started.ico" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="icons\bearnst_Connected.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="icons\bearnst_error_DisConnected.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="icons\Bearnst_StareBG.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="icons\bearnst_Started.ico">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>


	<ItemGroup>
		<Content Include="core\xray.exe">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="core\geoip.dat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="core\geosite.dat">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="core\wintun.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
